name: Dependency-Check Scan

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set NVD API Key
        run: echo "NVD_API_KEY=${{ secrets.NVD_API_KEY }}" >> $GITHUB_ENV

      - name: Install Dependency-Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v8.0.2/dependency-check-8.0.2-release.zip -O dependency-check.zip
          unzip -o dependency-check.zip -d $HOME
          chmod +x $HOME/dependency-check/dependency-check.sh

      - name: Run Dependency-Check
        run: |
          $HOME/dependency-check/dependency-check.sh \
            -s ./src \
            -o ./dependency-check-report \
            -f HTML,JSON

      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: ./dependency-check-report
