name: Dependency-Check Scan

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Download and Run Dependency-Check
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          # Download the latest release (Linux ZIP)
          curl -L -o dependency-check.zip https://github.com/DependencyCheck/dependency-check/releases/download/v8.3.2/dependency-check-8.3.2-release.zip
          
          unzip dependency-check.zip -d dependency-check
          chmod +x dependency-check/dependency-check/bin/dependency-check.sh
          
          ./dependency-check/dependency-check/bin/dependency-check.sh \
            --project "MyProject" \
            --scan . \
            --format "ALL" \
            --out dependency-check-report \
            --enableExperimental

      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report
