name: Dependency-Check Scan

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Dependency-Check
        uses: jeremylong/dependency-check-action@v3
        with:
          project: MyProject
          scan: .
          format: ALL
          enableExperimental: true
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}

      - name: Upload Dependency-Check Reports
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report
